### ISSUE TITLE
PLEASE PROVIDE DOC OR SOME EXAMPLES

### ISSUE THREAD

**Issue by cresusjpt** [SpinlockLabs/upnp.dart#7]
Hello, can someone provide documentation or explicit and commented example for utilisation ?

I'm working on an application that has to manage perfume diffusers. The diffuser can connect to wifi. Everything works well when the application is also connected to the same wifi but now I would like users to be able to automate the diffusion from outside or using mobile data. I know that by forwarding a port on the diffuser and using the public address this can be done. 
While googling I came across this upnp package but reading the examples I'm not sure how to use it.

**Comment by moda20** [comment]
There are examples within the examples folder, although i found multiple issues with this library and had to fix them myself.
check out my pull request if u intend to use this lib. https://github.com/SpinlockLabs/upnp.dart/pull/6

**Comment by cresusjpt** [comment]
@moda20 Thank you, I managed to do what I wanted to do
